version: '3.8'

services:
  app:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    
  db:
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    ports:
      - 3306:3306
    volumes:
      - ./schema:/docker-entrypoint-initdb.d