openapi: 3.0.0
info:
  version: 1.0.1
  title: User Balance Microservice
      
servers:
  - url: http://127.0.0.1:8080

tags:
  - name: service
    description: user interaction
  - name: server
    description: server interaction
paths:
  /health:
    get:
      tags: 
        - server
      summary: Server health check
      description: ""
      responses:
        "200":
          description: Server is healthy
          
  /balance:
    get:
      tags: 
        - service
      summary: Get balance by user id
      description: ""
      requestBody:
        $ref: "#/components/requestBodies/balanceGet"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: integer
                    format: float64
        "400":
          description: user does not exist or incorrect request
          content:
            application/json:
              schema:
                type: string
                format: string
        "500":
          description: internal error
          content:
            application/json:
              schema:
                type: string
                format: string

    put:
      tags: 
        - service
      summary: Append amount to balance by user id
      description: ""
      requestBody:
        $ref: "#/components/requestBodies/balancePut"
      responses:
        "200":
          description: successful operation
        "400":
          description: user does not exist or incorrect request
          content:
            application/json:
              schema:
                type: string
                format: string
        "500":
          description: internal error
          content:
            application/json:
              schema:
                type: string
                format: string
                
  /holder:
    post:
      tags: 
        - service
      summary: freezes the amount from the user's account
      description: ""
      requestBody:
        $ref: "#/components/requestBodies/holder"
      responses:
        "200":
          description: successful operation
        "400":
          description: incorrect request
          content:
            application/json:
              schema:
                type: string
                format: string
        "500":
          description: internal error
          content:
            application/json:
              schema:
                type: string
                format: string
    delete:
      tags:
        - service
      summary: unfreezes the amount from holder
      description: ""
      requestBody:
        $ref: "#/components/requestBodies/holder"
      responses:
        "200":
          description: successful operation
        "400":
          description: incorrect request
          content:
            application/json:
              schema:
                type: string
                format: string
        "500":
          description: internal error
          content:
            application/json:
              schema:
                type: string
                format: string
  
components:
  requestBodies:
    balanceGet:
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
      required: true
    balancePut:
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
              amount:
                type: integer
                format: float64
      description: User id and amount to append
      required: true
    holder:
      content:
        application/json:
          schema:
            type: object
            properties:              
              user_id:
                type: integer
                format: int64
              order_id:
                type: integer
                format: int64
              service_id:
                type: integer
                format: int64
              amount:
                type: integer
                format: float64
      required: true