openapi: 3.0.0
info:
  version: 1.0.0
  title: User Balance Microservice
      
servers:
  - url: http://127.0.0.1:8080

tags:
  - name: service
    description: user interaction
  - name: server
    description: server interaction
paths:
  /health:
    get:
      tags: 
        - server
      summary: Server health check
      description: ""
      responses:
        "200":
          description: Server is healthy
          
  /getBalance:
    get:
      tags: 
        - service
      summary: Get user balance by his id
      description: ""
      requestBody:
        $ref: "#/components/requestBodies/UserID"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
                
  /appendBalance:
    get:
      tags: 
        - service
      summary: Append amount to user balance by his id
      description: ""
      requestBody:
        $ref: "#/components/requestBodies/Append"
      responses:
        "200":
          description: successful operation
                
  /transferBalance:
    get:
      tags: 
        - service
      summary: Transfer amount from user to another user
      description: ""
      requestBody:
        $ref: "#/components/requestBodies/Transfer"
      responses:
        "200":
          description: successful operation
  
components:
  requestBodies:
    UserID:
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
      description: User id
      required: true
    Append:
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
              append:
                type: integer
                format: float64
      description: User id and amount to append
      required: true
    Transfer:
      content:
        application/json:
          schema:
            type: object
            properties:              
              receive_id:
                type: integer
                format: int64
              send_id:
                type: integer
                format: int64
              amount:
                type: integer
                format: float64
      description: Id receive user, send user and send amount
      required: true
      
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        balance:
          type: integer
          format: float64